# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_QrVyufjSbm3XKD5AaViWxS-sTLp_KV
"""

import math
import random
import datetime

question = [
    ("What is the square root of 817", math.sqrt(81)),
    ("What is 2 raised to power 67", math.pow(2, 6)),
    ("What is factorial of 57", math.factorial(5)),
    ("What is sin(90)?", round(math.sin(math.radians(90)), 2)),
    ("what is log base 10 of 1000?", math. log(1000))
]


random.shuffle(question)

print(" Welcome to Math Quiz Game!")
print("you have 5 question. Let' begin...\n")

score = 0
start_time = datetime.datetime.now()

for i, (q, ans) in enumerate(question, 1):
  print(f"Question {i}: {q}")
  user_ans = input("Your answer: ")

  try:
    if abs(float(user_answer) - float(ans) < 0.01):
           print(" Correct!\n")
           score += 1

    else:
           print(f"Worng! Correct Answer = {ans}\n")
  except:
           print(f"Invalid input! Correct answer = {ans}\n")


end_time = datetime.datetime.now()
time_taken = end_time - start_time

print("Quiz Over")
print(f"Your Score; {score} / {len(question)}")
print(f"Time Taken: {time_taken.seconds} Seconds")