# -*- coding: utf-8 -*-
"""ronak.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117c0Ear2ofx0KzpoekkguA1uKkDhxOvD
"""

import math
import time
import datetime
import random # Added random import

questions= [("what is the cube root of 512",math.cbrt(512)), # Changed maths.cube to math.cbrt
          ("what is the factorial of 6",math.factorial(6)),
           ("what is the square root of 100",math.sqrt(100)),
           ("what is the value of pi",math.pi), # Added comma
           ("what is the value of e",math.e)]

random.shuffle(questions)
print("welcome to the math quiz")
print("it's quiz time")
print("you have 5 questions.let's begin....\n") # Corrected typo "a 5 questions"
score=0
start_time=time.time()
# Removed redundant loop
# for question in questions
#     print(question[0])

for i ,(q,ans) in enumerate(questions,1):
    print(f"{i}:{q}")
    user_answer=input("your answer:")

    try:

      if abs(float(user_answer)-float(ans))<0.01:
        print("correct!\n")
        score += 1
      else:
          print(f" wrong!correct answer={ans}\n")

    except ValueError: # Catch ValueError specifically for invalid input
        print(f"invalid input! correct answer={ans}\n")

end_time = time.time() # Changed to time.time() for consistency
time_taken = end_time-start_time # Time difference is already in seconds

print("quiz over!")
print(f"your score:{score}/{len(questions)}")
print(f"time taken:{time_taken} seconds")