# -*- coding: utf-8 -*-
"""Vinayak_E.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mnjLiVNGk4C9CRZC4D0Fxa6O1NyXB8ZK
"""

import math
import random
import datetime

questions=[("what is the square root of 81?",math.sqrt(81)),
           ("what is 2 raised to power 6?",math.pow(2,6)),
           ("what is factorial of 5?",math.factorial(5)),
           ("what is (90°)?",round(math.sin(math.radians(90)),2)),
           ("What is log base 10 of 1000?",math.log10(1000))
           ]

random.shuffle(questions)

print("welcome to the math Quiz Game!")
print("You have 5 questions. Let's begin...\n")

score= 0
start_time = datetime.datetime.now()

for i, (q,ans) in enumerate(questions, 1):
    print(f"Q{i}:{q}")
    user_answer = input("Your answer:")

    try:

        if abs(float(user_answer)- float(ans)) < 0.01:
            print("Correct!\n")
            score += 1
        else:
            print(f"Wrong! Correct Answer = {ans}\n")
    except ValueError:
        print("Invalid input. Please enter a number.\n")


end_time = datetime.datetime.now()
time_taken = end_time - start_time

print("Quiz Over!")
print(f"Your Score:{score} / {len(questions)}")
print(f"Time Taken: {time_taken.seconds} seconds")

