# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wZJ986_10BqjsEWnTHjee8ZYoAII_7A3
"""

import math
import random
import datetime


questions=[
    ("what is the square root of 81",math.sqrt(81)),
    ("what is 2 raised to power 6",math.pow(2,6)),
    ("what is factorial of 5",math.factorial(5)),
    ("what is sin(90*)",round(math.sin(math.radians(90)),2)),
    ("what is log base 10 of 1000",math.log(1000,10)),
]

random.shuffle(questions)
print("welcome to the maths quiz game!")
print("you have 5 questions. let,s begin...\n")


score = 0
start_time = datetime.datetime.now()

for i, (q, ans) in enumerate(questions,1):
  print(f"Q{i}: {q}")
  user_answer = input("your answer:")

  try :
    if abs(float(user_answer) - float(ans)) < 0.01:
      print("correct answer!\n")
      score += 1
    else:
      print(f"wrong answer! the correct answer is {ans}\n")
  except ValueError:
      print(f"invalid input! the correct answer is {ans}\n")


end_time = datetime.datetime.now()
time_taken = (end_time - start_time).seconds

print("quiz over")
print(f"your score is {score}/{len(questions)}")
print(f"time taken: {time_taken} seconds")