# -*- coding: utf-8 -*-
"""Janvi_Sec B_CSE AIML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vRP7BgJoYIhFwwcsI9Zc833Tc-OLvC3m
"""

import os
with open("sample.txt", "w") as f:
     f.write("hello OS Module!")
print("Before rename:", os.listdir())
os.rename("sample.txt", "renamed.txt")
print("After rename:", os.listdir())
os.remove("renamed.txt")
print("After rename:", os.listdir())

import os
print("OS Name:", os.name)
print("PATH variable:", os.environ.get("PATH"))
print("Process ID:", os.getpid())
print("CPU Count:", os.cpu_count())
print("Current Working Directory:", os.getcwd)

import os
file_path = "demo.txt"
with open(file_path, "w") as f:
     f.write("Testing os.path")
print("Join path:", os.path.join("/content",(file_path)))

import sys
print("Python version:", sys.version)
print("Python version info:", sys.version_info)

print("System path Directories:")
for p in sys.path:
     print(p)
sys.path.append("/my/custom/path")
print("Updated Last Path:", sys.path[-1])

import math
print("square root of 16:", math.sqrt(16))
print("factorial of 5:", math.factorial(5))
print("ceil of 2.3:", math.ceil(2.3))
print("floor of 2.3:", math.floor(2.3))
print("pi value:", math.pi)
print("e value:", math.e)
print("log base 10 of 100:", math.log10(100))
print("log base 2 of 8:", math.log2(8))
print("sin 90:", math.sin(math.radians(90)))

import math
import random
import datetime
questions = [
    ("what is the sqaure root of 81?", math.sqrt(81)),
    ("what is the factorial of 5?", math.factorial(5)),
    ("what is 2 raised to power 6?", math.pow(2, 6)),
    ("what is sin(90)?", math.sin(math.radians(90))),
    ("what is log base 10 of 1000?", math.log10(1000))
]

random.shuffle(questions)
print("Welcome to the Math Quiz Game!")
print("You have 5 questions, Let`s begin...\n")

score = 0
start_time = datetime.datetime.now()
for i, (q, ans) in enumerate(questions, 1):
    print(f"Q{i}: {q}")
    user_answer = input("Your answer: ")

    try:
       if abs(float(user_answer) - float(ans)) < 0.01:
           print("✅ Correct!\n")
           score += 1
       else:
           print(f"❌ Wrong! Correct Answer = {ans}\n")
    except:
           print(f"⚠ Invalid input! Correct Answer = {ans}\n")


end_time = datetime.datetime.now()
time_taken = end_time - start_time

print("🎉 Quiz Over!")
print(f"Your Score: {score} / {len(questions)}")
print(f"Time Taken: {time_taken.seconds} seconds")