# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prReDhQP02e88dhVswXQg6ZSmsa598n4
"""

import math
import random
import datetime
questions=[
    ("what is the square root of 144?",math.sqrt(81)),
    ("what is 5 raised to power 7?",math.pow(5,7)),
    ("what is factorial to 5?",math.factorial(5)),
    ("what is cos(90)?",round(math.sin(math.radians(90)),2)),
    ("what is log base 10 of 100?",math.log10(100))
]

random.shuffle(questions)

print("welcome to the math quiz game!")
print("you have 5 questions .let's begin...\n")

score=0
start_time=datetime.datetime.now()

for i,(q,ans) in enumerate(questions,1):
  print(f"Q{i}: {q}")
  user_name=input("your answer:")

  try:
    if abs(float(user_answer)-float(ans)) < 0.01:
      print("Correct!\n")
      score+=1
    else:
      print("f Wrong! Correct Answer={ans}\n")
  except:
    print(f" Invalid input! Correct Answer{ans}\n")

end_time=datetime.datetime.now()
time_taken=end_time-start_time

print("Quiz Over!")
print(f"Your Score:{score} / {len(questions)}")
print(f"Time Taken: {time_taken.seconds}seconds")