# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17q29ADgiUXekydjD2_zUkpMg8GuJxCHR
"""

import math
import random
import datetime
questions = [
    ("What is the square root of 81?",math.sqrt(81)),
    ("What is 2 raised to power 6?",math.pow(2,6)),
    ("What is factorial to 5?",math.factorial(5)),
    ("What is sin(90)?",round(math.sin(math.radians(90)),2)),
    ("What is log base 10 of 1000?",math.log10(1000))
]
random.shuffle(questions)
print("Welcome to the Math Quiz Game!")
print("You have 5 questions.Let's begin...\n")
score = 0
start_time=datetime.datetime.now()
for i, (q,ans) in enumerate(questions, 1):
  print(f"Q{i}:{q}")
  user_answer = input("your answer:")
  try:
    if abs(float(user_answer)-float(ans))<0.01:
      print("Correct!\n")
      score +=1
    else:
        print(f"Wrong! Correct Answer = {ans}\n")
  except:
    print(f"Invalid input!Correct Answer = {ans}\n")
end_time = datetime.datetime.now()
time_taken = end_time - start_time
print("Quiz Over!")
print(f"Your Score: {score}/ {len(questions)}")
print(f"Time Taken: {time_taken.seconds} seconds")

