# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZViR92lOHj1NKQpnpWI85vKD3rhgAR_W
"""

import math
print("Pi:", math.pi)
print("Euler's number:", math.e)

print("sin(90):", math.sin(math.radians(90)))
print("cos(0)", math.cos(math.radians(0)))
print("tan(45)", math.tan(math.radians(45)))

import math
import random
import datetime

questions = [
    ("What is the square root of 81?", math.sqrt(81)),
    ("What is 2 raised to power 6?", math.pow(2, 6)),
    ("What is factorial of 5?", math.factorial(5)),
    ("What is sin(90)?", round(math.sin(math.radians(90)), 2)),
    ("What is log base 10 of 1000?", math.log10(1000))

]

random.shuffle(questions)

print("Welcome to the Math Quiz Game!")
print("You have five questions. Let's begin...\n")

score = 0
start_time = datetime.datetime.now()

for i, (q, ans) in enumerate(questions, 1):
  print(f"Q{i}: {q}")
  user_answer = input("Your answer: ")

  try:
    if abs(float(user_answer) - float(ans)) < 0.01:
         print("Correct!\n")
         score += 1
    else:
      print(f" Wrong! Correct Answer = {ans}\n")
  except ValueError:
    print(f"Invalid input! Correct Answer = {ans}\n")


end_time = datetime.datetime.now()
time_taken = end_time - start_time

print("Quiz OVer!")
print(f"Your Score: {score} / {len(questions)}")
print(f"Time Taken:{time_taken.seconds} seconds")