# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-OuKpEwXOM6WDz5vOGfzz3unq0r0irM
"""

import math
import random
import datetime
questions=[
 ("what is the square root of 64?",math.sqrt(64)) ,
 ("what is 2 raised to power 5?",math.pow(2,5)),
 ("what is the factorial of 7?",math.factorial(7)),
 ("what is cos(90)",round(math.cos(math.radians(90)),2)),
 ("what is log base 10 of 1000?",math.log10(1000))
]
random.shuffle(questions)
print("welcome to the math quiz game")
print("you have 5 questions.Let's begin...\n")
score=0
start_time=datetime.datetime.now()
for i,(q,ans) in enumerate(questions,1):
  print(f"Q{i}:{q}")
  user_answer=input("your answer:")
  try:
    if abs(float(user_answer)-float(ans))<0.01:
      print("correct\n")
      score+=1
    else:
      print(f"wrong! correct answer is {ans}\n")
  except ValueError:
    print(f"invalid input! correct answer is {ans}\n")
end_time=datetime.datetime.now()
time_taken=end_time-start_time
print("quiz over")
print(f"your score {score}/{len(questions)}")
print(f"time_taken: {time_taken.total_seconds()} seconds")

import datetime
now=datetime.datetime.now()
print("current date and time",now)
print("only date",now.date())
print("only time",now.time())

import math
print("natural log of e",math.log(math.e))
print("log base 10 of 100",math.log10(math.e))

import math
print("pi:",math.pi)
print("Euler's number:",math.e)

import math
print("square root of 16",math.sqrt(16))
print("2 raised to power 5:",math.pow(2,5))