# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kzl5ubHk9QJjYVpMsOtttw3rZgo6Txtf
"""

#square root andv power
import math
print("square root of 16:",math.sqrt(16))
print("2 raised to power 5:",math.pow(2,5))

#constants
print("pi:",math.pi)
print("Euler's number:",math.e)

#@title
#Trigometric functions
print("sin(90thita):",math.sin(math.radians(90)))
print("cos(0thiita):",math.cos(math.radians(0)))
print("tan(45thita):",math.tan(math.radians(45)))

#Logarithmic functions
print("natural log of e:",math.log(math.e))
print("log base 10m of 100:",math.log10(100))

#Raunding functions
print("Ceil of 4.2",math.ceil(4.2))
print("Floor of 4.8",math.floor(4.8))
print("Factorial of 5:",math.factorial(5))

import math
import random
import datetime

#List of questions(using math functions )
question = [
     ("what is the square root of 81?",math.sqrt(81)),
     ("what is 2 raised to power6?",math.pow(2,6)),
     ("what is factorial of 5?",math.factorial(5)),
     ("what is sin(90)?",round(math.sin(math.radians(90)),2)),
     ("what is log base 10 of 1000?",math.log10(1000))
  ]


#shuffle questions randomly
random.shuffle(question)

score =0
start_time=datetime.datetime.now()


for i, (q,ans) in enumerate(question,1):
   print(f"Q{i}: {q}")
   user_answer = input("your answer:")

   try:
    if abs (float(user_answer)-float(ans))<0.01: # Changed to <0.01 for a small tolerance
      print("correct!\n")
      score +=1

    else:
      print(f"wrong! correct answer={ans}\n")

   except ValueError: # Catch ValueError specifically for invalid float conversion
    print(f"invalid input!correct answer= {ans}\n")

end_time=datetime.datetime.now()
time_taken=end_time-start_time

print("Quiz over:")
print(f"your score:{score}/{len(question)}")
print(f"Time Taken:{time_taken.seconds} seconds") # Changed to .seconds for integer seconds