# -*- coding: utf-8 -*-
"""Vani_Section-B

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XVtWqR3kqPqhXQQdpop3Ub08Ff2CWVd9
"""

import math

#Square root and power
print("Square root of ")

print("pi:",math.pi)
print("Euler's number:",math.e)

#Shuffle questions randomly
random.shuffle(questions)

print("Welcome to the Math Quiz Game!")
print("You will be asked a series of math questions...\n")

score=0
start_time =datetime.datetime.now()
for i,(q,ans) in enumerate(questions,1):
  print(f"Q{i}:{q}")
  user_answer=input("Your answer:")

  try:
    if abs(float(user_answer)-float(ans))<0.01:
      print("Correct!\n")
      score+=1
      else:

import math
import random
import datetime

# List of questions (using math functions)
questions = [
    ("What is the square root of 81?", math.sqrt(81)),
    ("What is 2 raised to power 6?", math.pow(2, 6)),
    ("What is factorial of 5?", math.factorial(5)),
    ("What is sin(90°)?", round(math.sin(math.radians(90)), 2)),
    ("What is log base 10 of 1000?", math.log10(1000))
]

# Shuffle questions randomly
random.shuffle(questions)

print("Welcome to the Math Quiz Game!")
print("You have 5 questions. Let's begin...\n")

score = 0
start_time = datetime.datetime.now() # Start timer

for i, (q, ans) in enumerate(questions, 1):
    print(f"Q{i}: {q}")
    user_answer = input("Your answer: ")

    try:
        if abs(float(user_answer) - float(ans)) < 0.01: # Tolerance for float comparison
            print("Correct!\n")
            score += 1
        else:
            print(f"Wrong Answer = {ans}\n")
    except ValueError:
        print(f"Correct Answer = {ans}\n")

end_time = datetime.datetime.now() # End timer
time_taken = end_time - start_time

print("Quiz Over!")
print(f"Your Score: {score} / {len(questions)}")
print(f"Time Taken: {time_taken.total_seconds():.0f} seconds")